# .github/workflows/update-match-data.yml
name: Update Match Data from The Blue Alliance

on:
  workflow_dispatch:
    inputs:
      event_key:
        description: 'Event key to update (e.g., 2025txda)'
        required: true
        type: string

jobs:
  update-match-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Update match data
        env:
          TBA_API_KEY: ${{ secrets.TBA_API_KEY }}
          EVENT_KEY: ${{ github.event.inputs.event_key || '2025txbel' }}
        run: |
          npm install
          node update_match_data.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
